Remove traceback
jni/ipython-config pull request #1
Opened 2017-05-12 05:14 UTC by JohnnyTeutonic

Included a try and catch block inside the file 'ipython_config.py' to suppress the stacktrace from appearing inside an Ipython terminal in the scenario where certain custom imports such as line_profiler and cython are not inside the namespace of ipython_config, when an ipython terminal is first loaded. I have also made minor changes to the generate_failover_imports file - including the use of a suppress warnings clause instead of a try/catch clause to catch the exceptions generated for ModuleNotFoundError and ImportError. Should conform to pep8 standards.

2017-05-12 06:09 UTC, jni requested changes
@JohnnyTeutonic very nice and clean PR. =) I've suggested a few changes before I merge.

2017-05-12 06:09 UTC, jni commented on generate_failover_imports
> +            fout.write('from contextlib import suppress\n')
you probably only want to import this once, at the top, before the for-loop.

2017-05-12 06:09 UTC, jni commented on generate_failover_imports
> -import sys
I'm pretty sure you need to leave this in...?

2017-05-12 06:09 UTC, jni commented on generate_failover_imports
> +            fout.write('with suppress(ImportError, ModuleNotFoundError):\n')
So cool!

2017-05-12 06:09 UTC, jni commented on install
> +        import_file, output_file])
This line should align with the square, not circle, bracket (because it's still part of the list)

2017-05-12 06:09 UTC, jni commented on ipython_config.py
> +# c.TerminalIPythonApp.pylab = 'qt5'
I don't want this. =P

2017-05-12 06:09 UTC, jni commented on ipython_config.py
> +
Remove these empty lines

2017-05-12 06:34 UTC, JohnnyTeutonic commented
Okey dokey

On 12 May 2017 16:09, "Juan Nunez-Iglesias" <notifications@github.com>
wrote:

> *@jni* requested changes on this pull request.
>
> @JohnnyTeutonic <https://github.com/johnnyteutonic> very nice and clean
> PR. =) I've suggested a few changes before I merge.
> ------------------------------
>
> In generate_failover_imports
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157850>:
>
> >  infile = sys.argv[1]
>  outfile = sys.argv[2]
>
>  with open(infile) as fin:
>      with open(outfile, 'w') as fout:
>          for line in fin:
> -            fout.write('try:\n')
> +            fout.write('from contextlib import suppress\n')
>
> you probably only want to import this once, at the top, before the
> for-loop.
> ------------------------------
>
> In generate_failover_imports
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157870>:
>
> > @@ -1,15 +1,11 @@
>  #!/usr/bin/env python
>
> -import sys
>
> I'm pretty sure you need to leave this in...?
> ------------------------------
>
> In generate_failover_imports
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157893>:
>
> >  infile = sys.argv[1]
>  outfile = sys.argv[2]
>
>  with open(infile) as fin:
>      with open(outfile, 'w') as fout:
>          for line in fin:
> -            fout.write('try:\n')
> +            fout.write('from contextlib import suppress\n')
> +            fout.write('with suppress(ImportError, ModuleNotFoundError):\n')
>
> So cool!
> ------------------------------
>
> In install
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157956>:
>
> > @@ -18,7 +19,8 @@ startup_dir = os.path.join(profile_dir, 'startup')
>  shutil.copy(config_file, profile_dir)
>  # Then, generate the custom imports file
>  sp.call([os.path.join(rundir, 'generate_failover_imports'),
> -         import_file, output_file])
> +        import_file, output_file])
>
> This line should align with the square, not circle, bracket (because it's
> still part of the list)
> ------------------------------
>
> In ipython_config.py
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157982>:
>
> > @@ -62,7 +63,7 @@
>
>  # Pre-load matplotlib and numpy for interactive use, selecting a particular
>  # matplotlib backend and loop integration.
> -# c.TerminalIPythonApp.pylab = None
> +# c.TerminalIPythonApp.pylab = 'qt5'
>
> I don't want this. =P
> ------------------------------
>
> In ipython_config.py
> <https://github.com/jni/ipython-config/pull/1#discussion_r116157998>:
>
> > @@ -90,11 +91,25 @@
>  # Start IPython quickly by skipping the loading of config files.
>  # c.TerminalIPythonApp.quick = False
>
> +
> +
>
> Remove these empty lines
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jni/ipython-config/pull/1#pullrequestreview-37758767>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOIZLdzIPp3lkyeJ0rEkhGL1dk8vZHxhks5r4_eJgaJpZM4NY2R8>
> .
>

2017-05-16 13:06 UTC, jni approved these changes
👍 !

2017-05-16 13:06 UTC, merged

2017-05-16 13:07 UTC, jni commented
Awesome, thanks @JohnnyTeutonic! Be sure to do a `git checkout master; git pull upstream master` to get my matplotlib improvements as well! =)

2017-05-16 23:04 UTC, JohnnyTeutonic commented
Consider it done

On 16 May 2017 11:07 PM, "Juan Nunez-Iglesias" <notifications@github.com>
wrote:

> Awesome, thanks @JohnnyTeutonic <https://github.com/johnnyteutonic>! Be
> sure to do a git checkout master; git pull upstream master to get my
> matplotlib improvements as well! =)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jni/ipython-config/pull/1#issuecomment-301776244>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AOIZLWd-IVZoY1jN2iRJKJXJgr3rDRAVks5r6Z9-gaJpZM4NY2R8>
> .
>